In [2]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
from sklearn.decomposition import PCA

In [3]:
iris = datasets.load_iris()

In [27]:
type(iris)

sklearn.utils.Bunch

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
features = [x.replace(' (cm)', '') for x in iris['feature_names']]

In [9]:
features

['sepal length', 'sepal width', 'petal length', 'petal width']

In [12]:
iris['target_names'][1]

'versicolor'

In [13]:
def get_label(x):
    return iris['target_names'][int(x)]

get_label(2)

'virginica'

In [14]:
import numpy as np

data = pd.DataFrame(np.c_[iris['data'], iris['target']], columns=features + ['target'])

In [15]:
data.head()

sepal length  sepal width  petal length  petal width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [16]:
data['label'] = data['target'].apply(get_label)

In [17]:
data.head()

sepal length  sepal width  petal length  petal width  target   label
0           5.1          3.5           1.4          0.2     0.0  setosa
1           4.9          3.0           1.4          0.2     0.0  setosa
2           4.7          3.2           1.3          0.2     0.0  setosa
3           4.6          3.1           1.5          0.2     0.0  setosa
4           5.0          3.6           1.4          0.2     0.0  setosa

In [18]:
data.shape

(150, 6)

In [19]:
data.label.value_counts()

setosa        50
versicolor    50
virginica     50
Name: label, dtype: int64

In [20]:
for c in features:
    print(data[c].describe())
    print()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: sepal length, dtype: float64

count    150.000000
mean       3.057333
std        0.435866
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: sepal width, dtype: float64

count    150.000000
mean       3.758000
std        1.765298
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: petal length, dtype: float64

count    150.000000
mean       1.199333
std        0.762238
min        0.100000
25%        0.300000
50%        1.300000
75%        1.800000
max        2.500000
Name: petal width, dtype: float64



In [21]:

x = data.loc[:, features].values
y = data.loc[:, ['label']].values


In [22]:
x[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
x = StandardScaler().fit_transform(x)
# x_test = StandardScaler().transform(y_test) # NO we don't need it. And we don't have it.

In [25]:
x[:4]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ]])

In [26]:
tmp = pd.DataFrame(x, columns=features)
tmp.head()

sepal length  sepal width  petal length  petal width
0     -0.900681     1.019004     -1.340227    -1.315444
1     -1.143017    -0.131979     -1.340227    -1.315444
2     -1.385353     0.328414     -1.397064    -1.315444
3     -1.506521     0.098217     -1.283389    -1.315444
4     -1.021849     1.249201     -1.340227    -1.315444